---
- name: download the mediawiki installer package and paste it to the /tmp directory.
  unarchive:
    src: https://releases.wikimedia.org/mediawiki/1.29/mediawiki-1.29.0.tar.gz
    dest: /tmp
    mode: 0644
    remote_src: True

- name: create a mediawiki directory and copy the unarchived file.
  file:
    path: /var/www/html/mediawiki
    state: directory

- name: copy the archived file.
  shell: |
          mv mediawiki-1.29.0/* /var/www/html/mediawiki
          chown -R www-data:www-data /var/www/html/mediawiki/
          chmod -R 755 /var/www/html/mediawiki/
